export const lightTheme = {
    width: "100%",
    height: 50,
    border: 'none',
    backgroundColor: '#ffffff',
    placeholderTextColor: '#3a3a3a',
    selectedSingleValueTextColor: '#2b2b2b',
    arrowColor: '#5d5959',
    arrowColorHover: '#5d5959',
    indicatorSeparatorColor: '#afafaf',
    borderRadius: 4,
    listBorderRadius: 14,
    listBackgroundColor: '#ffffff',
    listItemTextColor: "#343434",
    listItemSelectedTextColor: "#343434",
    itemHoverBackgroundColor: '#ff9300',
    itemSelectedBackgroundColor: '#ffcfa1',
    itemHoverTextColor:  '#ffffff',
    listItemHeight: 50,
    boxShadow: "0 9px 15px 0 rgba(0, 0, 0, 0.12)",
    indicatorSeparatorDisplay: 'none'
}

export const darkTheme = {
    width: "100%",
    height: 50,
    border: 'none',
    backgroundColor: '#1c1c1c',
    placeholderTextColor: '#858585',
    selectedSingleValueTextColor: '#858585',
    arrowColor: '#b6b6b6',
    arrowColorHover: '#b6b6b6',
    indicatorSeparatorColor: '#afafaf',
    borderRadius: 4,
    listBorderRadius: 4,
    listBackgroundColor: '#333333',
    listItemTextColor: "#a2a2a2",
    listItemSelectedTextColor: "#ffffff",
    itemHoverBackgroundColor: '#ff9300',
    itemSelectedBackgroundColor: '#c56400',
    itemHoverTextColor:  '#ffffff',
    listItemHeight: 50,
    boxShadow: "20px 20px 20px 0 rgba(0, 0, 0, 0.11)",
    indicatorSeparatorDisplay: 'none'
}